cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('product-cart/', views.open_cart_view, name='product_cart'),
    path('add-to-cart/', views.add_product_to_cart, name='add_to_cart'),
    path('update-cart-item/<int:id>/', views.cart_update, name='update_cart_item')
]

djangoFinalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('', include('fixture.urls')),
                  path('', include('hospitality.urls')),
                  path('', include('user.urls')),
                  path('', include('django.contrib.auth.urls')),
                  path('', include('merch.urls')),
                  path('', include('h_bookings.urls')),
                  path('', include('cart.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merch/urls.py
from django.urls import path

from merch import views

urlpatterns = [
    path('merch/', views.MerchListView.as_view(), name='merch'),
    path('merch-real/', views.MerchRealListView.as_view(), name='merch_real'),
    path('merch-united/', views.MerchManUnitedListView.as_view(), name='merch_united'),
    path('merch-barcelona/', views.MerchBarcelonaListView.as_view(), name='merch_barcelona'),
    path('create-merch/', views.MerchCreateView.as_view(), name='create_merch'),
    path('update-merch/<int:pk>/', views.MerchUpdateView.as_view(), name='update_merch'),
    path('delete-merch/<int:pk>/', views.MerchDeleteView.as_view(), name='delete_merch'),
    path('buy-product/<int:pk>/', views.MerchDetailView.as_view(), name='buy_product'),
    path('checkout-merch/', views.checkout_merch, name='checkout_merch'),
]

merch/models.py
from django.db import models


class Merch(models.Model):
    size_ch = (('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'))
    name = models.CharField(max_length=150)
    header_image = models.ImageField(null=True, blank=True, upload_to='images/')
    price = models.IntegerField(null=False)
    size = models.CharField(max_length=30, default='M', choices=size_ch)
    description = models.TextField(max_length=1000, default='no description')
    for_vip = models.BooleanField(default=0)
    for_city = models.BooleanField(default=0)
    for_real = models.BooleanField(default=0)
    for_united = models.BooleanField(default=0)
    for_barcelona = models.BooleanField(default=0)

    def __str__(self):
        return self.name

merch/forms.py
from django import forms
from django.forms import TextInput, Textarea

from merch.models import Merch


class MerchForm(forms.ModelForm):
    class Meta:
        model = Merch
        fields = ['name', 'price', 'description', 'header_image', 'for_city', 'for_real',
                  'for_united', 'for_barcelona', 'for_vip']
        widgets = {
            'name': TextInput(attrs={'placeholder': 'please insert name', 'class': 'form-control'}),
            'price': TextInput(attrs={'type': 'number', 'class': 'form-control'}),
            'description': Textarea(attrs={'placeholder': 'please insert description', 'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(MerchForm, self).__init__(*args, **kwargs)

merch/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from merch.forms import MerchForm
from merch.models import Merch


def get_common_data(request, context=None):
    if context is None:
        context = {}
    return context


class MerchListView(ListView):
    template_name = 'merch/merch.html'
    model = Merch
    context_object_name = 'all_merch'


class MerchCreateView(CreateView):
    template_name = 'merch/create_merch.html'
    model = Merch
    form_class = MerchForm
    success_url = reverse_lazy('merch')


class MerchUpdateView(UpdateView):
    template_name = 'merch/update_merch.html'
    model = Merch
    form_class = MerchForm
    success_url = reverse_lazy('merch')
    context_object_name = 'all_merch'


class MerchDeleteView(DeleteView):
    template_name = 'merch/delete_merch.html'
    model = Merch
    success_url = reverse_lazy('merch')
    context_object_name = 'all_merch'


class MerchDetailView(DetailView):
    template_name = 'merch/product_page.html'
    model = Merch
    context_object_name = 'all_merch'


def checkout_merch(request):
    return render(request, 'checkout.html')


class MerchRealListView(ListView):
    template_name = 'merch/merch_real.html'
    model = Merch
    context_object_name = 'all_merch'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context = get_common_data(self.request, context)
        return context


class MerchManUnitedListView(ListView):
    template_name = 'merch/merch_man_united.html'
    model = Merch
    context_object_name = 'all_merch'


class MerchBarcelonaListView(ListView):
    template_name = 'merch/merch_barcelona.html'
    model = Merch
    context_object_name = 'all_merch'

templates/merch/checkout_merch_city.html
{% extends 'base.html' %}
{% block title %}
    Checkout
{% endblock %}
{% block content %}
    <div class="text-center card">
        <div class="card-body">
            <div class="card-title">CHECKOUT</div>
            <div class="card-text">Choose payment method</div>
            <button type="button" onclick="payPal()" class="btn btn-secondary">
                Pay Pal
                <img src="../../static/paypal-logo.png" alt="pay_pal" class="card_img">
            </button>
            <button type="button" onclick="creditCard()" class="btn btn-secondary">
                Credit card
                <img src="../../static/logo-visa.jpg" alt="visa" class="card_img">
                <img src="../../static/master-card-logo.png" alt="master_card" class="card_img">
            </button>
            <button type="button" onclick="paySafeCard()" class="btn btn-secondary">
                PaySafeCard
                <img src="../../static/paysasecard-logo.png" alt="pay_safe_card" class="card_img">
            </button>
            <button type="button" onclick="skrill()" class="btn btn-secondary">
                Skrill
                <img src="../../static/skrill-logo.png" alt="skrill" class="card_img">
            </button>
            <div class="card" id="credit_card">
                <form action="{% url 'final_details' %}">
                    <h3>BILLING INFORMATION</h3>
                    <label for="name">First Name</label>
                    <input id="name" type="text" required><br>

                    <label for="name">Last Name</label>
                    <input id="name" type="text" required><br>

                    <label for="name">Country</label>
                    <input id="name" type="text" required><br>

                    <h3>CREDIT CARD INFORMATION</h3>
                    <label for="name">Credit Card Number</label>
                    <input id="name" type="number" required><br>

                    <label for="name">Credit Card Number</label>
                    <input id="name" type="number" required><br>

                    <label for="name">Expiry Date</label>
                    <input id="name" type="date" required><br>

                    <label for="name">CVV</label>
                    <input id="name" type="number" required><br>

                    <input type="submit" value="Buy now" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelCard()" class="btn btn-danger">
                </form>
            </div>
            <div class="card" id="pay_pal">
                <form action="{% url 'final_details' %}">
                    <h3>CREDIT CARD INFORMATION</h3>

                    <label for="name">Credit Card Number</label>
                    <input id="name" type="number" required><br>

                    <label for="name">Expiry Date</label>
                    <input id="name" type="date" required><br>

                    <label for="name">CVV</label>
                    <input id="name" type="number" required><br>

                    <input type="submit" value="Buy now" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelPayPal()" class="btn btn-danger">
                </form>
            </div>
            <div class="card" id="pay_safe_card">
                <form action="{% url 'final_details' %}">
                    <label for="name">PIN CODE</label>
                    <input id="name" type="number" required min="16"><br>

                    <input type="submit" value="Buy now" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelpaySafeCard()" class="btn btn-danger">
                </form>
            </div>
            <div class="card" id="skrill">
                <form action="{% url 'final_details' %}">
                    <h3>LOGIN TO SKRILL ACCOUNT</h3>
                    <label for="name">USERNAME</label>
                    <input id="name" type="text" required><br>

                    <label for="name">PASSWORD</label>
                    <input id="name" type="password" required><br>

                    <input type="submit" value="Login" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelskrill()" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
    <style>
        #credit_card, #pay_pal, #pay_safe_card, #skrill {
            display: none;
        }

        .card_img {
            height: 20px;
            width: 30px;
        }
    </style>
    <script src="../../static/checkout.js"></script>
{% endblock %}

templates/merch/merch.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Club Merch
{% endblock %}
{% block content %}
    <h1>Club Merch</h1>
    {% if perms.merch.add_merch %}
        <a class="btn btn-sm btn-primary" href="{% url 'create_merch' %}">Create Merch</a><br>
    {% endif %}
    {% for merch in all_merch %}
        {% if merch.for_city %}
            {% if not merch.for_vip %}
                <div class="card" style="width: 18rem;margin-right: 20px;">
                    <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..." style="max-height: 280px">
                    <div class="card-body">
                        <h5 class="card-title">{{ merch.name }}</h5>
                        <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                            Price: {{ merch.price }} &#163</p>
                        <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                        <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy product</a>
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'add_to_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ merch.id }}">
                                <label>Nr of products:
                                    <input type="number" name="quantity" value="{{ quantity }}">
                                </label>
                                <button type="submit" class="btn btn-primary">Add to cart</button>
                            </form>
                        {% endif %}
                        {% if perms.merch.change_merch %}
                            <a class="btn btn-sm btn-primary"
                               href="{% url 'update_merch' merch.id %}">Update</a>
                        {% endif %}
                        {% if perms.merch.delete_merch %}
                            <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <h1>Club Merch VIP</h1>
    {% for merch in all_merch %}
        {% if merch.for_city %}
            {% if  merch.for_vip %}
                <div class="card" style="width: 18rem;margin-right: 20px;">
                    <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..." style="max-height: 280px">
                    <div class="card-body">
                        <h5 class="card-title">{{ merch.name }}</h5>
                        <div>
                            <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                                Price: {{ merch.price }} &#163</p>
                        </div>
                        <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                        {% if perms.user.vip_only %}
                            <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy product</a>
                        {% else %}
                            <button class="btn btn-sm btn-danger" disabled>Only for VIP</button>
                        {% endif %}
                        {% if user.is_authenticated %}
                            {% if perms.user.vip_only %}
                                <form method="post" action="{% url 'add_to_cart' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ merch.id }}" required>
                                    <label>Nr of products:
                                        <input type="number" name="quantity" min="1" value="{{ quantity }}" required>
                                    </label>
                                    <button type="submit" class="btn btn-primary">Add to cart</button>
                                </form>
                            {% endif %}
                        {% endif %}
                        {% if perms.merch.change_merch %}
                            <a class="btn btn-sm btn-primary"
                               href="{% url 'update_merch' merch.id %}">Update</a>
                        {% endif %}
                        {% if perms.merch.delete_merch %}
                            <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <style>

        * {
            margin: 0;
            padding: 0;
            border: 0;
            box-sizing: border-box
        }

        body {
            background-color: #dadde6;
            font-family: Arial, serif;
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }

        .card {
            display: inline-block;
            margin-bottom: 40px;
        }
    </style>
{% endblock %}

templates/merch/merch_barcelona.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Club Merch
{% endblock %}
{% block content %}
    <h1>Club Merch</h1>
    {% if perms.merch.add_merch %}
        <a class="btn btn-sm btn-primary" href="{% url 'create_merch' %}">Create Merch</a><br>
    {% endif %}
    {% for merch in all_merch %}
        {% if merch.for_barcelona %}
            {% if not merch.for_vip %}
                <div class="card" style="width: 18rem;margin-right: 20px;">
                    <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..." style="max-height: 280px">
                    <div class="card-body">
                        <h5 class="card-title">{{ merch.name }}</h5>
                        <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                            Price: {{ merch.price }} &#128</p>
                        <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                        <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy product</a>
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'add_to_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ merch.id }}">
                                <label>Nr of products:
                                    <input type="number" name="quantity" value="{{ quantity }}">
                                </label>
                                <button type="submit" class="btn btn-primary">Add to cart</button>
                            </form>
                        {% endif %}
                        {% if perms.merch.change_merch %}
                            <a class="btn btn-sm btn-primary"
                               href="{% url 'update_merch' merch.id %}">Update</a>
                        {% endif %}
                        {% if perms.merch.delete_merch %}
                            <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <h1>Club Merch VIP</h1>
    {% for merch in all_merch %}
        {% if merch.for_barcelona %}
            {% if  merch.for_vip %}
                {% if  merch.for_vip %}
                    <div class="card" style="width: 18rem;margin-right: 20px;">
                        <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..."
                             style="max-height: 280px">
                        <div class="card-body">
                            <h5 class="card-title">{{ merch.name }}</h5>
                            <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                                Price: {{ merch.price }} &#128</p>
                            <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                            {% if perms.user.vip_only %}
                                <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy
                                    product</a>
                            {% else %}
                                <button class="btn btn-sm btn-danger" disabled>Only for VIP</button>
                            {% endif %}
                            {% if user.is_authenticated %}
                                {% if perms.user.vip_only %}
                                    <form method="post" action="{% url 'add_to_cart' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="product_id" value="{{ merch.id }}" required>
                                        <label>Nr of products:
                                            <input type="number" name="quantity" value="{{ quantity }}" required>
                                        </label>
                                        <button type="submit" class="btn btn-primary">Add to cart</button>
                                    </form>
                                {% endif %}
                            {% endif %}
                            {% if perms.merch.change_merch %}
                                <a class="btn btn-sm btn-primary"
                                   href="{% url 'update_merch' merch.id %}">Update</a>
                            {% endif %}
                            {% if perms.merch.delete_merch %}
                                <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endif %}
    {% endfor %}
    <style>

        * {
            margin: 0;
            padding: 0;
            border: 0;
            box-sizing: border-box
        }

        body {
            background-color: #dadde6;
            font-family: Arial, serif;
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }

        .card {
            display: inline-block;
            margin-bottom: 40px;
        }
    </style>
{% endblock %}

templates/merch/merch_man_united.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Club Merch
{% endblock %}
{% block content %}
    <h1>Club Merch</h1>
    {% if perms.merch.add_merch %}
        <a class="btn btn-sm btn-primary" href="{% url 'create_merch' %}">Create Merch</a><br>
    {% endif %}
    {% for merch in all_merch %}
        {% if merch.for_united %}
            {% if not merch.for_vip %}
                <div class="card" style="width: 18rem;margin-right: 20px;">
                    <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..." style="max-height: 280px">
                    <div class="card-body">
                        <h5 class="card-title">{{ merch.name }}</h5>
                        <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                            Price: {{ merch.price }} &#163</p>
                        <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                        <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy product</a>
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'add_to_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ merch.id }}">
                                <label>Nr of products:
                                    <input type="number" name="quantity" value="{{ quantity }}">
                                </label>
                                <button type="submit" class="btn btn-primary">Add to cart</button>
                            </form>
                        {% endif %}
                        {% if perms.merch.change_merch %}
                            <a class="btn btn-sm btn-primary"
                               href="{% url 'update_merch' merch.id %}">Update</a>
                        {% endif %}
                        {% if perms.merch.delete_merch %}
                            <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <h1>Club Merch VIP</h1>
    {% for merch in all_merch %}
        {% if merch.for_united %}
            {% if  merch.for_vip %}
                {% if  merch.for_vip %}
                    <div class="card" style="width: 18rem;margin-right: 20px;">
                        <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..."
                             style="max-height: 280px">
                        <div class="card-body">
                            <h5 class="card-title">{{ merch.name }}</h5>
                            <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                                Price: {{ merch.price }} &#163</p>
                            <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                            {% if perms.user.vip_only %}
                                <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy
                                    product</a>
                            {% else %}
                                <button class="btn btn-sm btn-danger" disabled>Only for VIP</button>
                            {% endif %}
                            {% if user.is_authenticated %}
                                {% if perms.user.vip_only %}
                                    <form method="post" action="{% url 'add_to_cart' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="product_id" value="{{ merch.id }}" required>
                                        <label>Nr of products:
                                            <input type="number" name="quantity" value="{{ quantity }}" required>
                                        </label>
                                        <button type="submit" class="btn btn-primary">Add to cart</button>
                                    </form>
                                {% endif %}
                            {% endif %}
                            {% if perms.merch.change_merch %}
                                <a class="btn btn-sm btn-primary"
                                   href="{% url 'update_merch' merch.id %}">Update</a>
                            {% endif %}
                            {% if perms.merch.delete_merch %}
                                <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endif %}
    {% endfor %}
    <style>

        * {
            margin: 0;
            padding: 0;
            border: 0;
            box-sizing: border-box
        }

        body {
            background-color: #dadde6;
            font-family: Arial, serif;
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }

        .card {
            display: inline-block;
            margin-bottom: 40px;
        }
    </style>
{% endblock %}

templates/merch/merch_real.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Club Merch
{% endblock %}
{% block content %}
    <h1>Club Merch</h1>
    {% if perms.merch.add_merch %}
        <a class="btn btn-sm btn-primary" href="{% url 'create_merch' %}">Create Merch</a><br>
    {% endif %}
    {% for merch in all_merch %}
        {% if merch.for_real %}
            {% if not merch.for_vip %}
                <div class="card" style="width: 18rem;margin-right: 20px;">
                    <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..." style="max-height: 280px">
                    <div class="card-body">
                        <h5 class="card-title">{{ merch.name }}</h5>
                        <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                            Price: {{ merch.price }} &#128</p>
                        <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                        <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy product</a>
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'add_to_cart' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product_id" value="{{ merch.id }}">
                                <label>Nr of products:
                                    <input type="number" name="quantity" value="{{ quantity }}">
                                </label>
                                <button type="submit" class="btn btn-primary">Add to cart</button>
                            </form>
                        {% endif %}
                        {% if perms.merch.change_merch %}
                            <a class="btn btn-sm btn-primary"
                               href="{% url 'update_merch' merch.id %}">Update</a>
                        {% endif %}
                        {% if perms.merch.delete_merch %}
                            <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    <h1>Club Merch VIP</h1>
    {% for merch in all_merch %}
        {% if merch.for_real %}
            {% if  merch.for_vip %}
                {% if  merch.for_vip %}
                    <div class="card" style="width: 18rem;margin-right: 20px;">
                        <img src="{{ merch.header_image.url }}" class="card-img-top" alt="..."
                             style="max-height: 280px">
                        <div class="card-body">
                            <h5 class="card-title">{{ merch.name }}</h5>
                            <p class="card-text" style="margin-bottom:18px;margin-top: 14px">
                                Price: {{ merch.price }} &#128</p>
                            <p class="card-text">Available sizes: S/M/L/XL/XXL</p>
                            {% if perms.user.vip_only %}
                                <a class="btn btn-sm btn-primary" href="{% url 'buy_product' merch.id %}">Buy
                                    product</a>
                            {% else %}
                                <button class="btn btn-sm btn-danger" disabled>Only for VIP</button>
                            {% endif %}
                            {% if user.is_authenticated %}
                                {% if perms.user.vip_only %}
                                    <form method="post" action="{% url 'add_to_cart' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="product_id" value="{{ merch.id }}" required>
                                        <label>Nr of products:
                                            <input type="number" name="quantity" value="{{ quantity }}" required>
                                        </label>
                                        <button type="submit" class="btn btn-primary">Add to cart</button>
                                    </form>
                                {% endif %}
                            {% endif %}
                            {% if perms.merch.change_merch %}
                                <a class="btn btn-sm btn-primary"
                                   href="{% url 'update_merch' merch.id %}">Update</a>
                            {% endif %}
                            {% if perms.merch.delete_merch %}
                                <a class="btn btn-sm btn-danger" href="{% url 'delete_merch' merch.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endif %}
    {% endfor %}
    <style>

        * {
            margin: 0;
            padding: 0;
            border: 0;
            box-sizing: border-box
        }

        body {
            background-color: #dadde6;
            font-family: Arial, serif;
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }

        .card {
            display: inline-block;
            margin-bottom: 40px;
        }
    </style>
{% endblock %}