cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('product-cart/', views.open_cart_view, name='product_cart'),
    path('add-to-cart/', views.add_product_to_cart, name='add_to_cart'),
    path('update-cart-item/<int:id>/', views.cart_update, name='update_cart_item')
]

djangoFinalProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('', include('fixture.urls')),
                  path('', include('hospitality.urls')),
                  path('', include('user.urls')),
                  path('', include('django.contrib.auth.urls')),
                  path('', include('merch.urls')),
                  path('', include('h_bookings.urls')),
                  path('', include('cart.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('become-vip/', views.BecomeVIPListView.as_view(), name='become_vip'),
    path('checkout-vip/', views.checkout_vip, name='checkout_vip'),
    path('success-vip/', views.add_to_member, name='success_vip'),
    path('cancel-vip/', views.remove_from_member, name='cancel_vip_sub'),
    path('create-vip-card/', views.VIPCreateView.as_view(), name='create_vip_card'),
    path('delete-vip-card/<int:pk>/', views.VIPDeleteView.as_view(), name='delete_vip_card'),
    path('update-vip-card/<int:pk>/', views.VIPUpdateView.as_view(), name='update_vip_card'),
    path('contact-us/', views.contact_us, name='contact_us'),
    path('thank-you-for-contact/', views.thx_for_contact, name='thank_you_for_contact'),
    path('search-merch-city/', views.search_merch_city, name='search_merch_city'),
    path('search-merch-real/', views.search_merch_real, name='search_merch_real'),
    path('search-merch-united/', views.search_merch_united, name='search_merch_united'),
    path('search-merch-barcelona/', views.search_merch_barcelona, name='search_merch_barcelona'),
    path('search-hospitality/', views.search_hospitality_payed_city, name='search_hospitality_payed_city'),
    path('search-hospitality-barca/', views.search_hospitality_payed_barcelona,
         name='search_hospitality_payed_barcelona'),
    path('search-hospitality-real/', views.search_hospitality_vip_real, name='search_hospitality_vip_real'),
    path('search-hospitality-united/', views.search_hospitality_vip_united, name='search_hospitality_vip_united'),
    path('search-fixture-city/', views.search_fixture_city, name='search_fixture_city'),
    path('search-fixture-real/', views.search_fixture_real, name='search_fixture_real'),
    path('search-fixture-united/', views.search_fixture_man_united, name='search_fixture_united'),
    path('search-fixture-barcelona/', views.search_fixture_barcelona, name='search_fixture_barcelona'),
]

home/models.py
from django.db import models


class VIP(models.Model):
    vip_type_ch = (('Monthly', 'Monthly'), ('Yearly', 'Yearly'))
    title = models.CharField(max_length=150)
    price = models.IntegerField(null=False)
    description = models.TextField(max_length=1000, default='no description')
    vip_type = models.CharField(choices=vip_type_ch, max_length=30, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

home/forms.py
from django import forms
from django.forms import TextInput, Textarea, Select

from home.models import VIP


class VIPForm(forms.ModelForm):
    class Meta:
        model = VIP
        fields = ['title', 'price', 'description', 'vip_type']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'insert title', 'class': 'form-control'}),
            'price': TextInput(attrs={'type': 'number', 'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'vip_type': Select(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super(VIPForm, self).__init__(*args, **kwargs)

home/views.py
from django.shortcuts import render
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from fixture.models import Fixture
from home.forms import VIPForm
from home.models import VIP
from hospitality.models import HospitalityPayed, HospitalityVIP
from merch.models import Merch


def home_page(request):
    return render(request, 'home/home_page.html')


class BecomeVIPListView(ListView):
    template_name = 'home/become_vip.html'
    model = VIP
    context_object_name = 'all_vip'


class VIPCreateView(CreateView):
    template_name = 'home/create_vip.html'
    model = VIP
    form_class = VIPForm
    success_url = reverse_lazy('become_vip')
    context_object_name = 'all_vip'


class VIPUpdateView(UpdateView):
    template_name = 'home/update_vip.html'
    model = VIP
    form_class = VIPForm
    success_url = reverse_lazy('become_vip')
    context_object_name = 'all_vip'


class VIPDeleteView(DeleteView):
    template_name = 'home/delete_vip.html'
    model = VIP
    success_url = reverse_lazy('become_vip')
    context_object_name = 'all_vip'


def add_to_member(request):
    group = Group.objects.get(name='Member')
    user = request.user.id
    group.user_set.add(user)
    return render(request, 'home/vip_activation_success.html')


def remove_from_member(request):
    group = Group.objects.get(name='Member')
    user = request.user.id
    group.user_set.remove(user)
    return render(request, 'home/cancel_vip_sub.html')


def checkout_vip(request):
    return render(request, 'home/checkout_vip.html')


def contact_us(request):
    return render(request, 'home/contact_us.html')


def thx_for_contact(request):
    return render(request, 'home/thx_for_cont_us.html')


def search_merch_city(request):
    search = request.GET.get('search')
    merch_found = Merch.objects.filter(name__contains=search)
    return render(request, 'merch/merch.html', {'all_merch': merch_found})


def search_merch_real(request):
    search = request.GET.get('search')
    merch_found = Merch.objects.filter(name__contains=search)
    return render(request, 'merch/merch_real.html', {'all_merch': merch_found})


def search_merch_united(request):
    search = request.GET.get('search')
    merch_found = Merch.objects.filter(name__contains=search)
    return render(request, 'merch/merch_man_united.html', {'all_merch': merch_found})


def search_merch_barcelona(request):
    search = request.GET.get('search')
    merch_found = Merch.objects.filter(name__contains=search)
    return render(request, 'merch/merch_barcelona.html', {'all_merch': merch_found})


def search_hospitality_payed_city(request):
    search = request.GET.get('search')
    hospitality_found = HospitalityPayed.objects.filter(name_city__contains=search)
    return render(request, 'hospitality/hospitality_payed.html', {'all_hospitality': hospitality_found})


def search_hospitality_payed_barcelona(request):
    search = request.GET.get('search')
    hospitality_found = HospitalityPayed.objects.filter(name_barcelona__contains=search)
    return render(request, 'hospitality/hospitality_payed_barca.html', {'all_hospitality': hospitality_found})


def search_hospitality_vip_real(request):
    search = request.GET.get('search')
    hospitality_found = HospitalityVIP.objects.filter(name_real__contains=search)
    return render(request, 'hospitality/hospitality_vip.html', {'all_hospitality': hospitality_found})


def search_hospitality_vip_united(request):
    search = request.GET.get('search')
    hospitality_found = HospitalityVIP.objects.filter(name_united__contains=search)
    return render(request, 'hospitality/hospitality_vip_united.html', {'all_hospitality': hospitality_found})


def search_fixture_city(request):
    search = request.GET.get('search')
    fixture_found = Fixture.objects.filter(title_man_city__contains=search)
    return render(request, 'fixture/tickets_for_events.html', {'all_fixtures': fixture_found})


def search_fixture_real(request):
    search = request.GET.get('search')
    fixture_found = Fixture.objects.filter(title_real_madrid__contains=search)
    return render(request, 'fixture/ticket_for_real_madrid.html', {'all_fixtures': fixture_found})


def search_fixture_man_united(request):
    search = request.GET.get('search')
    fixture_found = Fixture.objects.filter(title_man_united__contains=search)
    return render(request, 'fixture/ticket_for_man_united.html', {'all_fixtures': fixture_found})


def search_fixture_barcelona(request):
    search = request.GET.get('search')
    fixture_found = Fixture.objects.filter(title_barcelona__contains=search)
    return render(request, 'fixture/ticket_for_fc_barcelona.html', {'all_fixtures': fixture_found})

templates/home/become_vip.html
{% extends 'base.html' %}
{% block title %}
    Become VIP
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Become VIP</h1>
        {% if perms.user.add_vip %}
            <a class="btn btn-sm btn-primary" href="{% url 'create_vip_card' %}">Create VIP Card</a>
        {% endif %}
        {% for vip in all_vip %}
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ vip.title }}</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">Price: {{ vip.price }} &#128</p>
                    <p class="card-text">Description: {{ vip.description }}</p>
                    <p class="card-text">Type: {{ vip.vip_type }}</p>
                    {% if perms.user.vip_only %}
                        <button type="button" data-bs-toggle="modal" class="btn btn-danger"
                                data-bs-target="#cancelModal" id="modalTrigger">
                            Cancel VIP subscription
                        </button>
                    {% else %}
                        <button type="button" data-bs-toggle="modal" class="btn btn-primary"
                                data-bs-target="#buyModal" id="modalTrigger">
                            Become VIP
                        </button>
                    {% endif %}
                    {% if perms.user.update_vip %}
                        <a class="btn btn-sm btn-primary" href="{% url 'update_vip_card' vip.id %}">Update</a>
                    {% endif %}
                    {% if perms.user.delete_vip %}
                        <a class="btn btn-sm btn-danger" href="{% url 'delete_vip_card' vip.id %}">Delete</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
    {# modal for buy #}
    <div class="modal fade" id="buyModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Buy ticket</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                         width="150">
                    <span>Purchase this VIP subscription?</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a href="{% url 'checkout_vip' %}" class="btn btn-primary">Go to checkout</a>
                </div>
            </div>
        </div>
    </div>
    {# modal for cancel #}
    <div class="modal fade" id="cancelModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Buy ticket</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle"
                         width="150">
                    <span>Cancel VIP subscription?</span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                    <a href="{% url 'cancel_vip_sub' %}" class="btn btn-primary">Yes</a>
                </div>
            </div>
        </div>
    </div>
    <style>

        * {
            margin: 0;
            padding: 0;
            border: 0;
            box-sizing: border-box
        }

        body {
            background-color: #dadde6;
            font-family: Arial, serif;
        }

        .container {
            width: 90%;
            margin: 100px auto
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }

        .card {
            margin-bottom: 40px;
        }
    </style>
{% endblock %}

templates/home/cancel_vip_sub.html
{% extends 'base.html' %}
{% block title %}
    VIP Subscription Canceled
{% endblock %}
{% block content %}
    <div class="text-center">
        <p>You are no longer VIP member</p>
        <p>You can re-subscribe any time</p>
        <p>Have a good day!</p>
        <a class="btn btn-primary" href="http://127.0.0.1:8000/">Go to home page</a>
    </div>
{% endblock %}

templates/home/checkout_vip.html
{% extends 'base.html' %}
{% block title %}
    Checkout
{% endblock %}
{% block content %}
    <div class="text-center card">
        <div class="card-body">
            <div class="card-title">CHECKOUT</div>
            <div class="card-text">Choose payment method</div>
            <button type="button" onclick="payPal()" class="btn btn-secondary">
                Pay Pal
                <img src="../../static/paypal-logo.png" alt="pay_pal" class="card_img">
            </button>
            <button type="button" onclick="creditCard()" class="btn btn-secondary">
                Credit card
                <img src="../../static/logo-visa.jpg" alt="visa" class="card_img">
                <img src="../../static/master-card-logo.png" alt="master_card" class="card_img">
            </button>
            <button type="button" onclick="paySafeCard()" class="btn btn-secondary">
                PaySafeCard
                <img src="../../static/paysasecard-logo.png" alt="pay_safe_card" class="card_img">
            </button>
            <button type="button" onclick="skrill()" class="btn btn-secondary">
                Skrill
                <img src="../../static/skrill-logo.png" alt="skrill" class="card_img">
            </button>
            <div class="card" id="credit_card">
                <form action="{% url 'success_vip' %}">
                    <h3>BILLING INFORMATION</h3>
                    <label for="name">First Name</label>
                    <input id="name" type="text" required><br>

                    <label for="name">Last Name</label>
                    <input id="name" type="text" required><br>

                    <label for="name">Country</label>
                    <input id="name" type="text" required><br>

                    <h3>CREDIT CARD INFORMATION</h3>
                    <label for="name">Credit Card Number</label>
                    <input id="name" type="number" required><br>

                    <label for="name">Credit Card Number</label>
                    <input id="name" type="number" required><br>

                    <label for="name">Expiry Date</label>
                    <input id="name" type="date" required><br>

                    <label for="name">CVV</label>
                    <input id="name" type="number" required><br>

                    <input type="submit" value="Buy now" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelCard()" class="btn btn-danger">
                </form>
            </div>
            <div class="card" id="pay_pal">
                <form action="{% url 'success_vip' %}">
                    <h3>CREDIT CARD INFORMATION</h3>

                    <label for="name">Credit Card Number</label>
                    <input id="name" type="number" required><br>

                    <label for="name">Expiry Date</label>
                    <input id="name" type="date" required><br>

                    <label for="name">CVV</label>
                    <input id="name" type="number" required><br>

                    <input type="submit" value="Buy now" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelPayPal()" class="btn btn-danger">
                </form>
            </div>
            <div class="card" id="pay_safe_card">
                <form action="{% url 'success_vip' %}">
                    <label for="name">PIN CODE</label>
                    <input id="name" type="number" required min="16"><br>

                    <input type="submit" value="Buy now" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelpaySafeCard()" class="btn btn-danger">
                </form>
            </div>
            <div class="card" id="skrill">
                <form action="{% url 'success_vip' %}">
                    <h3>LOGIN TO SKRILL ACCOUNT</h3>
                    <label for="name">USERNAME</label>
                    <input id="name" type="text" required><br>

                    <label for="name">PASSWORD</label>
                    <input id="name" type="password" required><br>

                    <input type="submit" value="Login" class="btn btn-primary">
                    <input type="button" value="Cancel" onclick="cancelskrill()" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
    <style>
        #credit_card, #pay_pal, #pay_safe_card, #skrill {
            display: none;
        }

        .card_img {
            height: 20px;
            width: 30px;
        }
    </style>
    <script src="../../static/checkout.js"></script>
{% endblock %}

templates/home/contact_us.html
{% extends 'base.html' %}
{% block title %}
    Contact us
{% endblock %}
{% block content %}
    <style>
        body {
            background-color: #dadde6;
            font-family: Arial, serif;
        }

        * {
            box-sizing: border-box;
        }

        input[type=text], select, textarea {
            width: 100%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-top: 6px;
            margin-bottom: 16px;
            resize: vertical;
        }

        input[type=submit] {
            background-color: #04AA6D;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        input[type=submit]:hover {
            background-color: #45a049;
        }

        .container {
            border-radius: 5px;
            background-color: #f2f2f2;
            padding: 20px;
        }

        h1 {
            text-transform: uppercase;
            font-weight: 900;
            border-left: 10px solid #fec500;
            padding-left: 10px;
            margin-bottom: 30px
        }
    </style>
    <h1>Contact Us</h1>

    <div class="container">
        <form method="post" action="{% url 'thank_you_for_contact' %}">
            <label for="fname">First Name</label>
            <input type="text" id="fname" name="firstname" placeholder="Your name.." required>

            <label for="lname">Last Name</label>
            <input type="text" id="lname" name="lastname" placeholder="Your last name.." required>

            <label for="mail">Email</label>
            <input type="text" id="mail" name="email" placeholder="Your email.." required>

            <label for="subject">Subject</label>
            <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"
                      required></textarea>

            <button class="btn btn-sm btn-primary" type="submit">Send message</button>
            <a class="btn btn-sm btn-secondary" href="{{ request.META.HTTP_REFERER|escape }}">Cancel</a>
        </form>
    </div>
{% endblock %}

templates/home/create_vip.html
{% extends 'base.html' %}
{% block title %}
    Create VIP card
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-sm btn-primary" type="submit">Create VIP card</button>
        <a class="btn btn-sm btn-secondary" href="{{ request.META.HTTP_REFERER|escape }}">Cancel</a>
    </form>
{% endblock %}

templates/home/delete_vip.html
{% extends 'base.html' %}
{% block title %}
    Delete VIP Card
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Do you really want to delete {{ all_hospitality.name }}?</p>
        <button class="btn btn-sm btn-danger" type="submit">Yes</button>
         <a class="btn btn-sm btn-secondary" href="{{ request.META.HTTP_REFERER|escape }}">No</a>
    </form>
{% endblock %}

templates/home/home_page.html
<!DOCTYPE html>
<html lang="en">
<title>Home Page</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
<body>
{% include 'navbar.html' %}
<div class="bgimg w3-display-container w3-text-white">
    <div class="w3-display-middle w3-jumbo">
        <p>CBITickets</p>
    </div>
    <div class="w3-display-topleft w3-container w3-xlarge">

    </div>
    <div class="w3-display-bottomleft w3-container">
        <p class="w3-large">&#169 Ciciovan Bogdan Ionut</p>
        <p class="w3-large">Email: ciciovan.bogdan@gmail.com</p>
        <p class="w3-large">Phone: 075286****</p>
{#        <p class="w3-large">Address: Loc.Baita Mun. Gherla Jud.Cluj</p>#}
        <p></p>
    </div>
</div>
<style>
    body, h1, h5 {
        font-family: "Raleway", sans-serif
    }

    body, html {
        height: 100%
    }

    .bgimg {
        background-image: url('../../static/football-stock-img.jpg');
        min-height: 100%;
        background-position: center;
        background-size: cover;
    }
</style>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/home/thx_for_cont_us.html
{% extends 'base.html' %}
{% block title %}
    Thanks for contacting us
{% endblock %}
{% block content %}
    <div class="text-center">
        <h1>Thank you for message!,</h1>
        <h3>We will replay to you shorter possible</h3>
        <h2>Have a good day! &#128512</h2>
    </div>
{% endblock %}

templates/home/update_vip.html
{% extends 'base.html' %}
{% block title %}
    Update VIP Card
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-sm btn-primary" type="submit">Save</button>
         <a class="btn btn-sm btn-secondary" href="{{ request.META.HTTP_REFERER|escape }}">Cancel</a>
    </form>
{% endblock %}

templates/home/vip_activation_success.html
{% extends 'base.html' %}
{% block title %}
    VIP Activation Success
{% endblock %}
{% block content %}
    <div class="text-center">
        <div>
            <span>Congratulations you are a VIP!!!</span>
            <ul>The benefits are:
                <li>You can buy VIP only tickets</li>
                <li>You can reserve hospitalitys on Real Madrid Stadium(Santiago Bernabéu)</li>
                <li>You can reserve hospitalitys on Man United Stadium(Old Trafford)</li>
                <li>Discounts on merch for your favourite team</li>
                <li>Other benefits coming soon...</li>
            </ul>
        </div>
        <a class="btn btn-primary" href="http://127.0.0.1:8000/">Go to home page</a>
    </div>
{% endblock %}